package io.github.trethore.graphene.internal.cef;

import io.github.trethore.graphene.api.browser.BrowserLoadFailureReason;
import io.github.trethore.graphene.api.browser.BrowserLoadTransition;
import java.util.OptionalInt;
import org.cef.handler.CefLoadHandler;
import org.cef.network.CefRequest;

final class GrapheneCefLoadEventMapper {
  private GrapheneCefLoadEventMapper() {}

  static BrowserLoadTransition transition(CefRequest.TransitionType transitionType) {
    if (transitionType == null) {
      return BrowserLoadTransition.UNKNOWN;
    }
    return switch (transitionType) {
      case TT_LINK -> BrowserLoadTransition.LINK;
      case TT_EXPLICIT -> BrowserLoadTransition.EXPLICIT;
      case TT_AUTO_SUBFRAME -> BrowserLoadTransition.AUTOMATIC_SUBFRAME;
      case TT_MANUAL_SUBFRAME -> BrowserLoadTransition.USER_INITIATED_SUBFRAME;
      case TT_FORM_SUBMIT -> BrowserLoadTransition.FORM_SUBMISSION;
      case TT_RELOAD -> BrowserLoadTransition.RELOAD;
    };
  }

  static BrowserLoadFailureReason failureReason(CefLoadHandler.ErrorCode errorCode) {
    if (errorCode == null) {
      return BrowserLoadFailureReason.UNKNOWN;
    }
    return switch (errorCode) {
      case ERR_ABORTED, ERR_CONTEXT_SHUT_DOWN, ERR_DNS_REQUEST_CANCELLED ->
          BrowserLoadFailureReason.CANCELED;
      case ERR_INVALID_ARGUMENT,
          ERR_INVALID_HANDLE,
          ERR_INVALID_URL,
          ERR_DISALLOWED_URL_SCHEME,
          ERR_UNKNOWN_URL_SCHEME,
          ERR_UNSAFE_PORT,
          ERR_METHOD_NOT_SUPPORTED ->
          BrowserLoadFailureReason.INVALID_REQUEST;
      case ERR_FILE_NOT_FOUND -> BrowserLoadFailureReason.NOT_FOUND;
      case ERR_TIMED_OUT, ERR_CONNECTION_TIMED_OUT, ERR_CACHE_LOCK_TIMEOUT, ERR_DNS_TIMED_OUT ->
          BrowserLoadFailureReason.TIMED_OUT;
      case ERR_ACCESS_DENIED,
          ERR_SSL_CLIENT_AUTH_PRIVATE_KEY_ACCESS_DENIED,
          ERR_NETWORK_ACCESS_DENIED,
          ERR_INVALID_AUTH_CREDENTIALS,
          ERR_UNSUPPORTED_AUTH_SCHEME,
          ERR_MISSING_AUTH_CREDENTIALS,
          ERR_MISCONFIGURED_AUTH_ENVIRONMENT ->
          BrowserLoadFailureReason.ACCESS_DENIED;
      case ERR_FILE_VIRUS_INFECTED,
          ERR_BLOCKED_BY_CLIENT,
          ERR_BLOCKED_BY_ADMINISTRATOR,
          ERR_BLOCKED_BY_RESPONSE,
          ERR_CLEARTEXT_NOT_PERMITTED,
          ERR_CERT_KNOWN_INTERCEPTION_BLOCKED ->
          BrowserLoadFailureReason.BLOCKED;
      case ERR_NETWORK_CHANGED, ERR_INTERNET_DISCONNECTED, ERR_NETWORK_IO_SUSPENDED ->
          BrowserLoadFailureReason.OFFLINE;
      case ERR_NAME_NOT_RESOLVED,
          ERR_HOST_RESOLVER_QUEUE_TOO_LARGE,
          ERR_NAME_RESOLUTION_FAILED,
          ERR_ICANN_NAME_COLLISION,
          ERR_DNS_MALFORMED_RESPONSE,
          ERR_DNS_SERVER_REQUIRES_TCP,
          ERR_DNS_CACHE_MISS,
          ERR_DNS_SEARCH_EMPTY,
          ERR_DNS_SORT_ERROR,
          ERR_DNS_SECURE_RESOLVER_HOSTNAME_RESOLUTION_FAILED,
          ERR_DNS_NAME_HTTPS_ONLY ->
          BrowserLoadFailureReason.NAME_RESOLUTION_FAILED;
      case ERR_SOCKET_NOT_CONNECTED,
          ERR_SOCKET_IS_CONNECTED,
          ERR_CONNECTION_CLOSED,
          ERR_CONNECTION_RESET,
          ERR_CONNECTION_REFUSED,
          ERR_CONNECTION_ABORTED,
          ERR_CONNECTION_FAILED,
          ERR_ADDRESS_INVALID,
          ERR_ADDRESS_UNREACHABLE,
          ERR_WINSOCK_UNEXPECTED_WRITTEN_BYTES,
          ERR_PRECONNECT_MAX_SOCKET_LIMIT,
          ERR_ADDRESS_IN_USE,
          ERR_SOCKET_SET_RECEIVE_BUFFER_SIZE_ERROR,
          ERR_SOCKET_SET_SEND_BUFFER_SIZE_ERROR,
          ERR_SOCKET_RECEIVE_BUFFER_SIZE_UNCHANGEABLE,
          ERR_SOCKET_SEND_BUFFER_SIZE_UNCHANGEABLE,
          ERR_TOO_MANY_RETRIES ->
          BrowserLoadFailureReason.CONNECTION_FAILED;
      case ERR_TUNNEL_CONNECTION_FAILED,
          ERR_PROXY_AUTH_UNSUPPORTED,
          ERR_SOCKS_CONNECTION_FAILED,
          ERR_SOCKS_CONNECTION_HOST_UNREACHABLE,
          ERR_PROXY_AUTH_REQUESTED,
          ERR_PROXY_CONNECTION_FAILED,
          ERR_MANDATORY_PROXY_CONFIGURATION_FAILED,
          ERR_UNABLE_TO_REUSE_CONNECTION_FOR_PROXY_AUTH,
          ERR_UNEXPECTED_PROXY_AUTH,
          ERR_PAC_SCRIPT_FAILED,
          ERR_NO_SUPPORTED_PROXIES,
          ERR_PAC_NOT_IN_DHCP,
          ERR_PROXY_AUTH_REQUESTED_WITH_NO_CONNECTION,
          ERR_PROXY_HTTP_1_1_REQUIRED,
          ERR_PAC_SCRIPT_TERMINATED ->
          BrowserLoadFailureReason.PROXY_FAILED;
      case ERR_SSL_PROTOCOL_ERROR,
          ERR_SSL_VERSION_OR_CIPHER_MISMATCH,
          ERR_SSL_RENEGOTIATION_REQUESTED,
          ERR_ALPN_NEGOTIATION_FAILED,
          ERR_SSL_NO_RENEGOTIATION,
          ERR_SSL_DECOMPRESSION_FAILURE_ALERT,
          ERR_SSL_BAD_RECORD_MAC_ALERT,
          ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED,
          ERR_SSL_DECRYPT_ERROR_ALERT,
          ERR_SSL_UNRECOGNIZED_NAME_ALERT,
          ERR_SSL_OBSOLETE_CIPHER,
          ERR_SSL_CLIENT_AUTH_NO_COMMON_ALGORITHMS,
          ERR_EARLY_DATA_REJECTED,
          ERR_WRONG_VERSION_ON_EARLY_DATA,
          ERR_TLS13_DOWNGRADE_DETECTED,
          ERR_SSL_KEY_USAGE_INCOMPATIBLE,
          ERR_INVALID_ECH_CONFIG_LIST,
          ERR_ECH_NOT_NEGOTIATED,
          ERR_UNEXPECTED_SECURITY_LIBRARY_STATUS,
          ERR_UNDOCUMENTED_SECURITY_LIBRARY_STATUS,
          ERR_INSECURE_RESPONSE ->
          BrowserLoadFailureReason.TLS_FAILED;
      case ERR_SSL_CLIENT_AUTH_CERT_NEEDED,
          ERR_BAD_SSL_CLIENT_AUTH_CERT,
          ERR_SSL_CLIENT_AUTH_CERT_NO_PRIVATE_KEY,
          ERR_PROXY_CERTIFICATE_INVALID,
          ERR_SSL_PINNED_KEY_NOT_IN_CERT_CHAIN,
          ERR_CLIENT_AUTH_CERT_TYPE_UNSUPPORTED,
          ERR_SSL_SERVER_CERT_CHANGED,
          ERR_SSL_CLIENT_AUTH_CERT_BAD_FORMAT,
          ERR_SSL_SERVER_CERT_BAD_FORMAT,
          ERR_CT_STH_PARSING_FAILED,
          ERR_CT_STH_INCOMPLETE,
          ERR_CT_CONSISTENCY_PROOF_PARSING_FAILED,
          ERR_ECH_FALLBACK_CERTIFICATE_INVALID,
          ERR_CERT_COMMON_NAME_INVALID,
          ERR_CERT_DATE_INVALID,
          ERR_CERT_AUTHORITY_INVALID,
          ERR_CERT_CONTAINS_ERRORS,
          ERR_CERT_NO_REVOCATION_MECHANISM,
          ERR_CERT_UNABLE_TO_CHECK_REVOCATION,
          ERR_CERT_REVOKED,
          ERR_CERT_INVALID,
          ERR_CERT_WEAK_SIGNATURE_ALGORITHM,
          ERR_CERT_NON_UNIQUE_NAME,
          ERR_CERT_WEAK_KEY,
          ERR_CERT_NAME_CONSTRAINT_VIOLATION,
          ERR_CERT_VALIDITY_TOO_LONG,
          ERR_CERTIFICATE_TRANSPARENCY_REQUIRED,
          ERR_CERT_SYMANTEC_LEGACY,
          ERR_CERT_END,
          ERR_QUIC_CERT_ROOT_NOT_KNOWN,
          ERR_NO_PRIVATE_KEY_FOR_CERT,
          ERR_ADD_USER_CERT_FAILED,
          ERR_PKCS12_IMPORT_BAD_PASSWORD,
          ERR_PKCS12_IMPORT_FAILED,
          ERR_IMPORT_CA_CERT_NOT_CA,
          ERR_IMPORT_CERT_ALREADY_EXISTS,
          ERR_IMPORT_CA_CERT_FAILED,
          ERR_IMPORT_SERVER_CERT_FAILED,
          ERR_PKCS12_IMPORT_INVALID_MAC,
          ERR_PKCS12_IMPORT_INVALID_FILE,
          ERR_PKCS12_IMPORT_UNSUPPORTED,
          ERR_KEY_GENERATION_FAILED,
          ERR_PRIVATE_KEY_EXPORT_FAILED,
          ERR_SELF_SIGNED_CERT_GENERATION_FAILED,
          ERR_CERT_DATABASE_CHANGED ->
          BrowserLoadFailureReason.CERTIFICATE_FAILED;
      case ERR_WS_PROTOCOL_ERROR,
          ERR_WS_UPGRADE,
          ERR_INVALID_REDIRECT,
          ERR_TOO_MANY_REDIRECTS,
          ERR_UNSAFE_REDIRECT,
          ERR_INVALID_RESPONSE,
          ERR_INVALID_CHUNKED_ENCODING,
          ERR_EMPTY_RESPONSE,
          ERR_REQUEST_RANGE_NOT_SATISFIABLE,
          ERR_MALFORMED_IDENTITY,
          ERR_CONTENT_DECODING_FAILED,
          ERR_HTTP2_PROTOCOL_ERROR,
          ERR_ENCODING_DETECTION_FAILED,
          ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH,
          ERR_INCOMPLETE_HTTP2_HEADERS,
          ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION,
          ERR_RESPONSE_HEADERS_MULTIPLE_LOCATION,
          ERR_HTTP2_SERVER_REFUSED_STREAM,
          ERR_HTTP2_PING_FAILED,
          ERR_CONTENT_LENGTH_MISMATCH,
          ERR_INCOMPLETE_CHUNKED_ENCODING,
          ERR_QUIC_PROTOCOL_ERROR,
          ERR_RESPONSE_HEADERS_TRUNCATED,
          ERR_QUIC_HANDSHAKE_FAILED,
          ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY,
          ERR_HTTP2_FLOW_CONTROL_ERROR,
          ERR_HTTP2_FRAME_SIZE_ERROR,
          ERR_HTTP2_COMPRESSION_ERROR,
          ERR_HTTP_1_1_REQUIRED,
          ERR_INVALID_HTTP_RESPONSE,
          ERR_CONTENT_DECODING_INIT_FAILED,
          ERR_HTTP2_RST_STREAM_NO_ERROR_RECEIVED,
          ERR_HTTP2_STREAM_CLOSED,
          ERR_HTTP_RESPONSE_CODE_FAILURE,
          ERR_QUIC_GOAWAY_REQUEST_CAN_BE_RETRIED,
          ERR_INVALID_SIGNED_EXCHANGE,
          ERR_INVALID_WEB_BUNDLE,
          ERR_TRUST_TOKEN_OPERATION_FAILED,
          ERR_TRUST_TOKEN_OPERATION_SUCCESS_WITHOUT_SENDING_REQUEST ->
          BrowserLoadFailureReason.PROTOCOL_FAILED;
      case ERR_FILE_TOO_BIG,
          ERR_UPLOAD_FILE_CHANGED,
          ERR_FILE_EXISTS,
          ERR_FILE_PATH_TOO_LONG,
          ERR_FILE_NO_SPACE,
          ERR_UPLOAD_STREAM_REWIND_NOT_SUPPORTED ->
          BrowserLoadFailureReason.FILE_FAILED;
      case ERR_CACHE_MISS,
          ERR_CACHE_READ_FAILURE,
          ERR_CACHE_WRITE_FAILURE,
          ERR_CACHE_OPERATION_NOT_SUPPORTED,
          ERR_CACHE_OPEN_FAILURE,
          ERR_CACHE_CREATE_FAILURE,
          ERR_CACHE_RACE,
          ERR_CACHE_CHECKSUM_READ_FAILURE,
          ERR_CACHE_CHECKSUM_MISMATCH,
          ERR_CACHE_AUTH_FAILURE_AFTER_READ,
          ERR_CACHE_ENTRY_NOT_SUITABLE,
          ERR_CACHE_DOOM_FAILURE,
          ERR_CACHE_OPEN_OR_CREATE_FAILURE ->
          BrowserLoadFailureReason.CACHE_FAILED;
      case ERR_INSUFFICIENT_RESOURCES,
          ERR_OUT_OF_MEMORY,
          ERR_TEMPORARILY_THROTTLED,
          ERR_MSG_TOO_BIG,
          ERR_WS_THROTTLE_QUEUE_TOO_LARGE,
          ERR_NO_BUFFER_SPACE,
          ERR_RESPONSE_HEADERS_TOO_BIG,
          ERR_RESPONSE_BODY_TOO_BIG_TO_DRAIN ->
          BrowserLoadFailureReason.RESOURCE_EXHAUSTED;
      case ERR_NONE,
          ERR_IO_PENDING,
          ERR_FAILED,
          ERR_UNEXPECTED,
          ERR_NOT_IMPLEMENTED,
          ERR_READ_IF_READY_NOT_IMPLEMENTED ->
          BrowserLoadFailureReason.UNKNOWN;
    };
  }

  static OptionalInt diagnosticCode(CefLoadHandler.ErrorCode errorCode) {
    return errorCode == null ? OptionalInt.empty() : OptionalInt.of(errorCode.getCode());
  }

  static OptionalInt httpStatus(int httpStatusCode) {
    return httpStatusCode > 0 ? OptionalInt.of(httpStatusCode) : OptionalInt.empty();
  }
}
