package tytoo.grapheneui.internal.input.keyboard;

import org.lwjgl.glfw.GLFW;

import java.util.HashMap;
import java.util.Map;

final class GrapheneMacKeyCodeMapping {
    private static final int[][] GLFW_KEY_MAPPINGS = {
            {GLFW.GLFW_KEY_A, 0x00},
            {GLFW.GLFW_KEY_S, 0x01},
            {GLFW.GLFW_KEY_D, 0x02},
            {GLFW.GLFW_KEY_F, 0x03},
            {GLFW.GLFW_KEY_H, 0x04},
            {GLFW.GLFW_KEY_G, 0x05},
            {GLFW.GLFW_KEY_Z, 0x06},
            {GLFW.GLFW_KEY_X, 0x07},
            {GLFW.GLFW_KEY_C, 0x08},
            {GLFW.GLFW_KEY_V, 0x09},
            {GLFW.GLFW_KEY_B, 0x0B},
            {GLFW.GLFW_KEY_Q, 0x0C},
            {GLFW.GLFW_KEY_W, 0x0D},
            {GLFW.GLFW_KEY_E, 0x0E},
            {GLFW.GLFW_KEY_R, 0x0F},
            {GLFW.GLFW_KEY_Y, 0x10},
            {GLFW.GLFW_KEY_T, 0x11},
            {GLFW.GLFW_KEY_1, 0x12},
            {GLFW.GLFW_KEY_2, 0x13},
            {GLFW.GLFW_KEY_3, 0x14},
            {GLFW.GLFW_KEY_4, 0x15},
            {GLFW.GLFW_KEY_6, 0x16},
            {GLFW.GLFW_KEY_5, 0x17},
            {GLFW.GLFW_KEY_EQUAL, 0x18},
            {GLFW.GLFW_KEY_9, 0x19},
            {GLFW.GLFW_KEY_7, 0x1A},
            {GLFW.GLFW_KEY_MINUS, 0x1B},
            {GLFW.GLFW_KEY_8, 0x1C},
            {GLFW.GLFW_KEY_0, 0x1D},
            {GLFW.GLFW_KEY_RIGHT_BRACKET, 0x1E},
            {GLFW.GLFW_KEY_O, 0x1F},
            {GLFW.GLFW_KEY_U, 0x20},
            {GLFW.GLFW_KEY_LEFT_BRACKET, 0x21},
            {GLFW.GLFW_KEY_I, 0x22},
            {GLFW.GLFW_KEY_P, 0x23},
            {GLFW.GLFW_KEY_ENTER, 0x24},
            {GLFW.GLFW_KEY_L, 0x25},
            {GLFW.GLFW_KEY_J, 0x26},
            {GLFW.GLFW_KEY_APOSTROPHE, 0x27},
            {GLFW.GLFW_KEY_K, 0x28},
            {GLFW.GLFW_KEY_SEMICOLON, 0x29},
            {GLFW.GLFW_KEY_BACKSLASH, 0x2A},
            {GLFW.GLFW_KEY_COMMA, 0x2B},
            {GLFW.GLFW_KEY_SLASH, 0x2C},
            {GLFW.GLFW_KEY_N, 0x2D},
            {GLFW.GLFW_KEY_M, 0x2E},
            {GLFW.GLFW_KEY_PERIOD, 0x2F},
            {GLFW.GLFW_KEY_TAB, 0x30},
            {GLFW.GLFW_KEY_SPACE, 0x31},
            {GLFW.GLFW_KEY_GRAVE_ACCENT, 0x32},
            {GLFW.GLFW_KEY_BACKSPACE, 0x33},
            {GLFW.GLFW_KEY_ESCAPE, 0x35},
            {GLFW.GLFW_KEY_RIGHT_SUPER, 0x36},
            {GLFW.GLFW_KEY_LEFT_SUPER, 0x37},
            {GLFW.GLFW_KEY_LEFT_SHIFT, 0x38},
            {GLFW.GLFW_KEY_CAPS_LOCK, 0x39},
            {GLFW.GLFW_KEY_LEFT_ALT, 0x3A},
            {GLFW.GLFW_KEY_LEFT_CONTROL, 0x3B},
            {GLFW.GLFW_KEY_RIGHT_SHIFT, 0x3C},
            {GLFW.GLFW_KEY_RIGHT_ALT, 0x3D},
            {GLFW.GLFW_KEY_RIGHT_CONTROL, 0x3E},
            {GLFW.GLFW_KEY_F17, 0x40},
            {GLFW.GLFW_KEY_KP_DECIMAL, 0x41},
            {GLFW.GLFW_KEY_KP_MULTIPLY, 0x43},
            {GLFW.GLFW_KEY_KP_ADD, 0x45},
            {GLFW.GLFW_KEY_KP_DIVIDE, 0x4B},
            {GLFW.GLFW_KEY_KP_ENTER, 0x4C},
            {GLFW.GLFW_KEY_KP_SUBTRACT, 0x4E},
            {GLFW.GLFW_KEY_F18, 0x4F},
            {GLFW.GLFW_KEY_F19, 0x50},
            {GLFW.GLFW_KEY_KP_EQUAL, 0x51},
            {GLFW.GLFW_KEY_KP_0, 0x52},
            {GLFW.GLFW_KEY_KP_1, 0x53},
            {GLFW.GLFW_KEY_KP_2, 0x54},
            {GLFW.GLFW_KEY_KP_3, 0x55},
            {GLFW.GLFW_KEY_KP_4, 0x56},
            {GLFW.GLFW_KEY_KP_5, 0x57},
            {GLFW.GLFW_KEY_KP_6, 0x58},
            {GLFW.GLFW_KEY_KP_7, 0x59},
            {GLFW.GLFW_KEY_F20, 0x5A},
            {GLFW.GLFW_KEY_KP_8, 0x5B},
            {GLFW.GLFW_KEY_KP_9, 0x5C},
            {GLFW.GLFW_KEY_F5, 0x60},
            {GLFW.GLFW_KEY_F6, 0x61},
            {GLFW.GLFW_KEY_F7, 0x62},
            {GLFW.GLFW_KEY_F3, 0x63},
            {GLFW.GLFW_KEY_F8, 0x64},
            {GLFW.GLFW_KEY_F9, 0x65},
            {GLFW.GLFW_KEY_F11, 0x67},
            {GLFW.GLFW_KEY_F13, 0x69},
            {GLFW.GLFW_KEY_F16, 0x6A},
            {GLFW.GLFW_KEY_F14, 0x6B},
            {GLFW.GLFW_KEY_F10, 0x6D},
            {GLFW.GLFW_KEY_F12, 0x6F},
            {GLFW.GLFW_KEY_F15, 0x71},
            {GLFW.GLFW_KEY_INSERT, 0x72},
            {GLFW.GLFW_KEY_HOME, 0x73},
            {GLFW.GLFW_KEY_PAGE_UP, 0x74},
            {GLFW.GLFW_KEY_DELETE, 0x75},
            {GLFW.GLFW_KEY_F4, 0x76},
            {GLFW.GLFW_KEY_END, 0x77},
            {GLFW.GLFW_KEY_F2, 0x78},
            {GLFW.GLFW_KEY_PAGE_DOWN, 0x79},
            {GLFW.GLFW_KEY_F1, 0x7A},
            {GLFW.GLFW_KEY_LEFT, 0x7B},
            {GLFW.GLFW_KEY_RIGHT, 0x7C},
            {GLFW.GLFW_KEY_DOWN, 0x7D},
            {GLFW.GLFW_KEY_UP, 0x7E}
    };

    private static final int[][] CHARACTER_MAPPINGS = {
            {' ', 0x31},
            {'0', 0x1D},
            {')', 0x1D},
            {'1', 0x12},
            {'!', 0x12},
            {'2', 0x13},
            {'@', 0x13},
            {'3', 0x14},
            {'#', 0x14},
            {'4', 0x15},
            {'$', 0x15},
            {'5', 0x17},
            {'%', 0x17},
            {'6', 0x16},
            {'^', 0x16},
            {'7', 0x1A},
            {'&', 0x1A},
            {'8', 0x1C},
            {'*', 0x1C},
            {'9', 0x19},
            {'(', 0x19},
            {'a', 0x00},
            {'A', 0x00},
            {'b', 0x0B},
            {'B', 0x0B},
            {'c', 0x08},
            {'C', 0x08},
            {'d', 0x02},
            {'D', 0x02},
            {'e', 0x0E},
            {'E', 0x0E},
            {'f', 0x03},
            {'F', 0x03},
            {'g', 0x05},
            {'G', 0x05},
            {'h', 0x04},
            {'H', 0x04},
            {'i', 0x22},
            {'I', 0x22},
            {'j', 0x26},
            {'J', 0x26},
            {'k', 0x28},
            {'K', 0x28},
            {'l', 0x25},
            {'L', 0x25},
            {'m', 0x2E},
            {'M', 0x2E},
            {'n', 0x2D},
            {'N', 0x2D},
            {'o', 0x1F},
            {'O', 0x1F},
            {'p', 0x23},
            {'P', 0x23},
            {'q', 0x0C},
            {'Q', 0x0C},
            {'r', 0x0F},
            {'R', 0x0F},
            {'s', 0x01},
            {'S', 0x01},
            {'t', 0x11},
            {'T', 0x11},
            {'u', 0x20},
            {'U', 0x20},
            {'v', 0x09},
            {'V', 0x09},
            {'w', 0x0D},
            {'W', 0x0D},
            {'x', 0x07},
            {'X', 0x07},
            {'y', 0x10},
            {'Y', 0x10},
            {'z', 0x06},
            {'Z', 0x06},
            {';', 0x29},
            {':', 0x29},
            {'=', 0x18},
            {'+', 0x18},
            {',', 0x2B},
            {'<', 0x2B},
            {'-', 0x1B},
            {'_', 0x1B},
            {'.', 0x2F},
            {'>', 0x2F},
            {'/', 0x2C},
            {'?', 0x2C},
            {'`', 0x32},
            {'~', 0x32},
            {'[', 0x21},
            {'{', 0x21},
            {'\\', 0x2A},
            {'|', 0x2A},
            {']', 0x1E},
            {'}', 0x1E},
            {'\'', 0x27},
            {'"', 0x27},
            {'\b', 0x33},
            {'\t', 0x30},
            {'\r', 0x24},
            {0x1B, 0x35}
    };

    private static final Map<Integer, Integer> BY_GLFW_KEY = createByGlfwKey();
    private static final Map<Character, Integer> BY_CHARACTER = createByCharacter();

    private GrapheneMacKeyCodeMapping() {
    }

    static int resolveFromGlfwKey(int keyCode) {
        return BY_GLFW_KEY.getOrDefault(keyCode, 0);
    }

    static int resolveFromCharacter(char character) {
        return BY_CHARACTER.getOrDefault(character, 0);
    }

    private static Map<Integer, Integer> createByGlfwKey() {
        Map<Integer, Integer> mappings = new HashMap<>();
        for (int[] mapping : GLFW_KEY_MAPPINGS) {
            mappings.put(mapping[0], mapping[1]);
        }

        return Map.copyOf(mappings);
    }

    private static Map<Character, Integer> createByCharacter() {
        Map<Character, Integer> mappings = new HashMap<>();
        for (int[] mapping : CHARACTER_MAPPINGS) {
            mappings.put((char) mapping[0], mapping[1]);
        }

        return Map.copyOf(mappings);
    }
}
