name: publish
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish-maven-central:
    uses: ./.github/workflows/publish-maven-central.yml
    secrets: inherit

  publish-github:
    needs: publish-maven-central
    uses: ./.github/workflows/publish-github.yml
    secrets: inherit
